[site]
title = "Yan Yang"
description = "PhD @ Academy of Mathematics and Systems Science (AMSS), Chinese Academy of Sciences (CAS)"
favicon = "/badminton_1.svg"
last_updated = "November 18, 2025"

[author]
name = "Yan Yang (杨俨)"
title = "PhD Student"
institution = "Academy of Mathematics and Systems Science (AMSS) • Chinese Academy of Sciences (CAS)"
avatar = "/bio_Changsha_YY.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "yangyan@amss.ac.cn"
location = "Beijing, China"
location_url = "https://maps.app.goo.gl/o4hfhdAZq6ggaUEDA" 
location_details = [
  "No. 55 Zhongguancun East Road",      # 中关村东路55号
  "Haidian District, Beijing 100190"    # 海淀区，邮编
]
google_scholar = "https://scholar.google.com.co/citations?user=gga4vtUAAAAJ&hl=vi"
github = "https://github.com/UCAS-YanYang"
linkedin = ""
orcid = ""

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

# [[navigation]]
# title = "Teaching"
# type = "page"
# target = "teaching"
# href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

# [[navigation]]
# title = "Services"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
