[[news]]
date = "2025"
content = "11-29: New preprint - [â€œVariational analysis of determinantal varietiesâ€](https://arxiv.org/abs/2511.22613)"

[[news]]
date = "2025"
content = "09-30: Awarded the Hua Luogeng Scholarship at AMSS ğŸ–ï¸"

[[news]]
date = "2025"
content = "05-05: Awarded the SIAM Certificate of Recognition ğŸ–ï¸"

[[news]]
date = "2025"
content = "01-24: New preprint - [â€œA space-decoupling framework for optimization on bounded-rank matrices with orthogonally invariant constraintsâ€](https://arxiv.org/abs/2501.13830)"


[[news]]
date = "2025"
content = "01-23: New paper accepted in AISTATS 2025 - [â€œBilevel Reinforcement Learning via the Development of Hyper-gradient without Lower-Level Convexityâ€](https://arxiv.org/abs/2405.19697)"

[[news]]
date = "2025"
content = "01-23: New paper accepted in ICLR 2025 - [â€œLancBiO: dynamic Lanczos-aided bilevel optimization via Krylov subspaceâ€](https://arxiv.org/abs/2404.03331)"


# ğŸ‰